### ISSUE TITLE
new test: HTTP -> HTTPS redirect

### ISSUE THREAD

**Issue by Geal** [sozu-proxy/sozu-integration-tests#11]
- set up an app with two frontends
  - one in HTTP, with HTTPS redirection
  - one in HTTPS
- the client does a HTTP request
- verify that the proxy answers with a 301 to the HTTPS version
- the client does a HTTPS request
- verify that the server gets the correct protocol in the `Forwarded-*` headers

**Comment by NotBad4U** [comment]
WIP in [https-redirect](https://github.com/sozu-proxy/sozu-integration-tests/tree/https-redirect) branch.
The blocking points are:
- We need to create a CA
- We have to generate certificate signed with the CA

**Comment by NotBad4U** [comment]
Done in #22
