### ISSUE TITLE
new test: circuit breaker

### ISSUE THREAD

**Issue by Geal** [sozu-proxy/sozu-integration-tests#14]
- set up an application with a backend, but do not start that backend
- the client sends a request
- check that sozu sends back a 503 response after some attempted backend connections

**Comment by NotBad4U** [comment]
Done in 156fb56

**Comment by Geal** [comment]
one request should be enough, because the circuit breaker is per request: for one request, we try to connect to backend servers `CONN_RETRIES` times, and if it still fails, then sozu returns a 503

**Comment by NotBad4U** [comment]
Modify in 743f31a

**Comment by Geal** [comment]
:+1:
