### ISSUE TITLE
add a way to run directly from a Dockerfile

### ISSUE THREAD

**Issue by Geal** [sozu-proxy/sozu-integration-tests#3]
The current code downloads the latest container from hub.docker.com, but to test with a local sozu repository, we should be able to point to a path on the filesystem to a Dockerfile that would be used instead.
See https://www.testcontainers.org/usage/dockerfile.html for more info on running testcontainers from a Dockerfile

**Comment by NotBad4U** [comment]
We know how to do that because we already done that for the NodeJs backend [here](https://github.com/sozu-proxy/sozu-integration-tests/blob/e701b09395bbdfbd8cdf9fa3e2275845801428d5/src/main/java/NodeBackendContainer.java#L15)

**Comment by Geal** [comment]
To clarify: we need a way to override which sozu container is used.
Normal case: download one from hub.docker.com
When a specific command line flag or env variable is used to point a path to a Dockerfile: use that Dockerfile for the sozu container in all tests

**Comment by NotBad4U** [comment]
Done in `255a17e` , we can now define the Dockerfile path with the SOZU_DOCKERFILE env variable.
