### ISSUE TITLE
new test: chunked response

### ISSUE THREAD

**Issue by Geal** [sozu-proxy/sozu-integration-tests#5]
- the client does a `GET /` request
- the server sends a file as chunked response
- the client receives all the packets and verify the file hash (we should have received the entire file)

it might be interesting to have variations in chunk size and frequency (example: send some 1 byte chunks, or wait a few milliseconds before sending the next chunk)

**Comment by Geal** [comment]
example server code:

```js
const fs = require('fs');

require('http').createServer((req, res) => {
  console.log(req.method);
  console.log(req.headers);
	if (req.method === 'POST') {
		let body = '';
		req.on('data', chunk => {
			console.log("received chunk: "+chunk.length);
			//console.log("chunk");
			body += chunk.toString(); // convert Buffer to string
		});
		req.on('end', () => {
			console.log("end");
			//console.log(body);
			res.end('ok');
		});
	} else {
		//console.log(req);
		//req.pipe(res);
		const src = fs.createReadStream('../lib/src/network/protocol/http.rs', { highWaterMark: 4096 });
		//src.pipe(res);
		src.on('data', (chunk) => {
			console.log("chunk: "+chunk.length);
			res.write(chunk);
		});
		src.on('end', () => {
			console.log("end");
			res.end();
		})
	}
}).listen(1026);
```

**Comment by NotBad4U** [comment]
Done in f421858

**Comment by NotBad4U** [comment]
I close this one with the merge of #23

**Comment by Geal** [comment]
technically, this does not verify that the response is chunked, only the presence of the header. But if the client is spec compliant it should refuse a content that is not chunked.
Also, there should be no `Content-length` header in a chunked response
