### ISSUE TITLE
new test: path begin and keep alive

### ISSUE THREAD

**Issue by Geal** [sozu-proxy/sozu-integration-tests#7]
- set up two applications
  - one with only a domain name for its frontend
  - one with the same domain name, and a path prefix
- the client does a request with the domain name (but not the path prefix of the second app), making sure it's in keep-alive
- we verify that the response comes from the first application and is correct
- the client does a new request, on the same connection, with the domain name and the path prefix
- - we verify that the response comes from the second application and is correct

**Comment by NotBad4U** [comment]
Done in f4bb5b8
Can you take a look [SozuContainerTest.java#L162](https://github.com/sozu-proxy/sozu-integration-tests/blob/f4bb5b8e7e42efe99c4fcdf07ee334f5eb0dcaa4/src/test/java/SozuContainerTest.java#L162)

**Comment by Geal** [comment]
:+1:
